---
- name: nginx_webservers
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:

    - name: Установка Nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Запуск и включение автозагрузки Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes