- name: install_nginx (nginx)
  hosts: nginx
  become: yes
  gather_facts: yes
  tasks:

    - name: Создать index.html с именем хоста
      ansible.builtin.copy:
        content: "<h1>Hello from {{ ansible_hostname }}</h1>\n"
        dest: /var/www/html/index.html

    - name: Перезапустить nginx
      ansible.builtin.service:
        name: nginx
        state: restarted